Repository jenkinsci/build-monitor-plugin, pull requests merged in 2021-11, with the labels that each got.

#496 Remove all usages of Guava
  build-monitor-acceptance/pom.xml
  build-monitor-acceptance/src/main/java/com/smartcodeltd/jenkinsci/plugins/build_monitor/model/ProjectInformation.java
  build-monitor-acceptance/src/main/java/com/smartcodeltd/jenkinsci/plugins/build_monitor/model/ProjectStatus.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/jenkins/JenkinsInstance.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/jenkins/TestEnvironment.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/jenkins/client/JenkinsClient.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/jenkins/environment/UpdateCenter.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/jenkins/environment/rules/FindFreePort.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/jenkins/environment/rules/InstallPluginsFromDisk.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/jenkins/environment/rules/InstallPluginsFromUpdateCenter.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/utils/ListFunctions.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/screenplay/jenkins/actions/EnterCode.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/screenplay/jenkins/targets/Setting.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/screenplay/jenkins/tasks/configuration/TodoList.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/screenplay/jenkins/tasks/configuration/build_steps/GroovyScript.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/screenplay/jenkins/tasks/configuration/build_steps/ShellScript.java
  build-monitor-acceptance/src/test/java/net/serenitybdd/integration/jenkins/environment/UpdateCenterUnitTest.java
  build-monitor-plugin/pom.xml
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/Config.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/api/Success.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/culprits/BuildCulpritsAbstractBuild.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/culprits/BuildCulpritsRetriever.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/culprits/BuildCulpritsWorkflowRun.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/functions/NullSafety.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/installation/BuildMonitorInstallation.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/BuildView.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/BuildViewModel.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/BuildingPredicate.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobView.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobViews.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/NullBuildView.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/CanBeClaimed.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/CanBeDiagnosedForProblems.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasBadgesBadgePlugin.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasBadgesGroovyPostbuildPlugin.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasHeadline.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/KnowsCurrentBuildsDetails.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/headline/HeadlineOfAborted.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/headline/HeadlineOfExecuting.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/headline/HeadlineOfFailing.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/headline/HeadlineOfFixed.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasBadgesGroovyPostbuildPluginTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/BadgeBadgePluginRecipe.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/BadgeGroovyPostbuildRecipe.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/BuildStateRecipe.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/ConfigStateRecipe.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/JobStateRecipe.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/JobViewRecipe.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/Loops.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/Sugar.java
  pom.xml
Labels: internal

#497 Remove PowerMock
  .github/dependabot.yml
  build-monitor-acceptance/pom.xml
  build-monitor-plugin/pom.xml
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugin/assetbundler/PathToAssetTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/BuildMonitorDescriptorTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/installation/BuildMonitorInstallationTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/pipeline/BreadthFirstNodeTraversalTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/pipeline/PipelineHelperTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/BuildViewTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobViewTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/CanBeClaimedTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/CanBeDiagnosedForProblemsTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasBadgesBadgePluginTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasHeadlineShowingAbortedBuildDetails.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasHeadlineShowingFailedBuildDetailsTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasHeadlineShowingFixedBuildDetailsTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasHeadlineShowingRunningBuildDetailsTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasHeadlineWhichShowsNothingTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/KnowsCurrentBuildsDetailsTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/KnowsLastCompletedBuildDetailsTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/readability/ListerTest.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/BadgeBadgePluginRecipe.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/BuildStateRecipe.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/syntacticsugar/JobStateRecipe.java
  pom.xml
Labels: internal

#504 Upgrade various Java dependencies
  .github/dependabot.yml
  build-monitor-acceptance/pom.xml
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/jenkins/JenkinsInstance.java
  build-monitor-acceptance/src/test/java/environment/JenkinsSandbox.java
  build-monitor-plugin/pom.xml
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/api/Respond.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/api/Success.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobView.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobViewSerialiser.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/CanBeClaimed.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/CanBeDiagnosedForProblems.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasBadgesBadgePlugin.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/KnowsCurrentBuildsDetails.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/KnowsLastCompletedBuildDetails.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/headline/Headline.java
Labels: dependencies, java

#513 Upgrade various additional Java dependencies
  .github/dependabot.yml
  build-monitor-acceptance/pom.xml
  build-monitor-plugin/pom.xml
  pom.xml
Labels: dependencies, java

#517 Compile less
  .github/dependabot.yml
  build-monitor-acceptance/pom.xml
  build-monitor-plugin/pom.xml
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugin/assetbundler/Dispatcher.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugin/assetbundler/PathToAsset.java
  build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugin/assetbundler/filters/LessCSS.java
  build-monitor-plugin/src/main/resources/com/smartcodeltd/jenkinsci/plugins/buildmonitor/BuildMonitorView/index.jelly
  build-monitor-plugin/src/main/webapp/less/layout/dashboard.less
  build-monitor-plugin/src/main/webapp/less/layout/index.less
  build-monitor-plugin/src/main/webapp/less/layout/widgets.less
  build-monitor-plugin/src/main/webapp/less/module/footer.less
  build-monitor-plugin/src/main/webapp/less/module/index.less
  build-monitor-plugin/src/main/webapp/less/module/widget/basic.less
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugin/assetbundler/OsSpecific.java
  build-monitor-plugin/src/test/java/com/smartcodeltd/jenkinsci/plugin/assetbundler/PathToAssetTest.java
  pom.xml
Labels: bug

#516 Improve acceptance tests speed
  .github/workflows/main.yaml
  .gitignore
  build-monitor-acceptance/pom.xml
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/jenkins/environment/rules/InstallPlugins.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/integration/jenkins/environment/rules/InstallPluginsFromDisk.java
  build-monitor-acceptance/src/main/java/net/serenitybdd/screenplay/jenkins/tasks/configuration/build_steps/GroovyScriptThat.java
  build-monitor-acceptance/src/test/java/features/BuilMonitorAcceptanceTest.java
  build-monitor-acceptance/src/test/java/features/BuildMonitorShouldBeEasyToSetUp.java
  build-monitor-acceptance/src/test/java/features/ProjectStatusShouldBeEasyToDetermine.java
  build-monitor-acceptance/src/test/java/features/ShouldDescribeEachProject.java
  build-monitor-acceptance/src/test/java/features/ShouldDisplayBadges.java
  build-monitor-acceptance/src/test/java/features/ShouldDisplayConcurrentBuilds.java
  build-monitor-acceptance/src/test/java/features/ShouldDisplayPipelineStage.java
  build-monitor-acceptance/src/test/java/features/ShouldSupportCloudBeesFolders.java
  build-monitor-acceptance/src/test/java/features/ShouldSupportExternalProjects.java
  build-monitor-acceptance/src/test/java/features/ShouldTellWhatBrokeTheBuild.java
  build-monitor-acceptance/src/test/java/features/ShouldTellWhoIsFixingTheBrokenBuild.java
  build-monitor-acceptance/src/test/resources/serenity.conf
Labels: test
